#!/usr/bin/env node
/**
 * gen-docs.mjs: regenerate the error reference in docs/TROUBLESHOOTING.md from the message
 * catalog (scripts/lib/messages.mjs). The selftest fails when the two differ, so every message a
 * user can see always has a documented cause and fix.
 *
 *   node scripts/gen-docs.mjs
 */
import { readFileSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";
import { MESSAGES } from "./lib/messages.mjs";
import { isMain } from "./lib/cli.mjs";

const GROUPS = [
  ["IHC00", "Intercom access"], ["IHC01", "Config"], ["IHC02", "Manifest and features"], ["IHC03", "Publishing"], ["IHC04", "Publishing"],
  ["IHC05", "Pre-write check"], ["IHC06", "Git and pull requests"], ["IHC07", "Git and pull requests"], ["IHC08", "Hooks"], ["IHC09", "Environment"],
  ["IHC10", "Coverage gate"], ["IHC11", "Coverage gate"],
];
const esc = (s) => String(s).replace(/\|/g, "\\|");

export function renderTroubleshooting() {
  const L = ["<!-- BEGIN GENERATED ERRORS -->", "<!-- Generated by scripts/gen-docs.mjs from scripts/lib/messages.mjs. Do not edit by hand. -->", ""];
  let current = null;
  for (const [code, m] of Object.entries(MESSAGES)) {
    const group = GROUPS.find(([p]) => code.startsWith(p))?.[1] ?? "Other";
    if (group !== current) {
      if (current) L.push("");
      L.push(`### ${group}`, "", "| Code | Message | Cause | Fix |", "|---|---|---|---|");
      current = group;
    }
    const level = m.level === "warn" ? " (warning)" : m.level === "gate" ? " (gate)" : "";
    L.push(`| **${code}**${level} | ${esc(m.text)} | ${esc(m.cause)} | ${esc(m.fix)} |`);
  }
  L.push("", "<!-- END GENERATED ERRORS -->");
  return L.join("\n");
}

if (isMain(import.meta.url)) {
  const path = join(dirname(fileURLToPath(import.meta.url)), "..", "docs", "TROUBLESHOOTING.md");
  const doc = readFileSync(path, "utf8");
  const next = doc.replace(/<!-- BEGIN GENERATED ERRORS -->[\s\S]*<!-- END GENERATED ERRORS -->/, renderTroubleshooting());
  writeFileSync(path, next);
  console.log(`[gen-docs] ${Object.keys(MESSAGES).length} messages written to docs/TROUBLESHOOTING.md`);
}
